import React, { useEffect, useState, useRef } from 'react';
import type { AgentState, AuditEvent, RunInput } from '../shared/agent';
import {VoiceInput} from './voice';
export function Tasks({ model }: { model: string }) {
  const [state, setState] = useState<AgentState>({ runs: [], active: null, approvals: [] });
  const [selected, setSelected] = useState<string | null>(null); const selectedRef = useRef<string | null>(null);
  const [events, setEvents] = useState<AuditEvent[]>([]); const [workspace, setWorkspace] = useState('');
  const [mode, setMode] = useState<RunInput['mode']>('host'); const [network, setNetwork] = useState(false);
  const [goal, setGoal] = useState(''); const [error, setError] = useState(''); const [starting, setStarting] = useState(false);
  const [preview, setPreview] = useState<string | null>(null);
  const fail = (e: unknown) => setError(e instanceof Error ? e.message : String(e));
  const select = async (id: string) => { selectedRef.current = id; setSelected(id); const list = await window.nix.runEvents(id); if (selectedRef.current === id) setEvents(list); };
  useEffect(() => {
    let alive = true; let loading = false, again = false;
    const refresh = async () => {
      if (loading) { again = true; return; } loading = true;
      try { do { again = false; const next = await window.nix.agentState(); if (!alive) return; setState(next); const id = selectedRef.current ?? next.runs[0]?.id; if (id) await select(id); } while (again && alive); } catch(e) { if (alive) fail(e); } finally { loading = false; }
    };
    const off = window.nix.onAgent(() => void refresh()); void refresh(); void window.nix.workspace().then(setWorkspace).catch(fail);
    return () => { alive = false; off(); };
  }, []);
  const current = state.runs.find(r => r.id === selected);
  const begin = async () => { setStarting(true); setError(''); try { const id = await window.nix.startRun({ goal, model, mode, workspace: mode === 'mock' ? '.' : workspace, network }); await select(id); setGoal(''); } catch(e) { fail(e); } finally { setStarting(false); } };
  const approvals = state.approvals;
  const artifacts = events.flatMap(e => { try { return e.type === 'tool.result' ? JSON.parse(e.data).artifacts ?? [] : []; } catch { return []; } }) as string[];
  return <div className="task-view">
    <section className="task-controls panel"><div className="section-label">EXECUTION ENVIRONMENT</div><div className="task-options"><label>Environment<select aria-label="Environment" value={mode} disabled={!!state.active} onChange={e => setMode(e.target.value as RunInput['mode'])}><option value="host">Host · PowerShell</option><option value="docker">Docker · Linux</option><option value="mock">Mock · No side effects</option></select></label><button disabled={!!state.active} onClick={() => void window.nix.pickWorkspace().then(path => { if (path) setWorkspace(path); }).catch(fail)}>Choose workspace</button>{mode === 'docker' && <label className="check-label"><input type="checkbox" checked={network} disabled={!!state.active} onChange={e => setNetwork(e.target.checked)}/> Container network</label>}</div><p className="workspace-path">{workspace || 'Choose a folder for file and coding tasks.'}</p><p className="scope-note">{mode === 'host' ? 'Host commands use your Windows account and can access outside this folder. Every write and command requires approval.' : mode === 'docker' ? 'Linux containers mount only this workspace. Docker must be running with python:3.13-slim installed. No host fallback.' : 'Mock tools exercise approvals and failures without changing files.'}</p></section>
    {error && <div className="error" role="alert">{error}</div>}
    <div className="task-columns"><section className="run-list panel"><div className="section-label">TASK HISTORY <span>{state.runs.length.toString().padStart(2, '0')}</span></div>{state.runs.length === 0 && <p className="empty-nav">Your task attempts and evidence will appear here.</p>}{state.runs.map(run => <button key={run.id} className={`run-item ${run.id === selected ? 'selected' : ''}`} onClick={() => void select(run.id).catch(fail)}><strong>{run.goal}</strong><small><span className={`status ${run.status}`}>{run.status}</span> · {run.mode}</small></button>)}</section>
    <section className="run-detail panel"><div className="section-label">{current ? 'EXECUTION RECORD' : 'READY FOR YOUR NEXT TASK'}<span className="hud-tick">●</span></div>{!current ? <div className="task-empty"><img src="./nix-emblem.png" alt="NiX emblem"/><h2>Intent into action.</h2><p>Give NiX a concrete goal. Inspect each proposed action, follow its execution, and review the evidence.</p></div> : <><h2>{current.goal}</h2><div className="run-meta"><span className={`status ${current.status}`}>{current.status}</span><span>{current.model}</span><span>Run {current.id.slice(0,8)}</span></div>{current.summary && <div className="run-summary">{current.summary}</div>}<div className="run-actions">{state.active === current.id && <button onClick={() => void window.nix.cancelRun(current.id).catch(fail)}>Stop task</button>}{!state.active && current.status !== 'completed' && <button onClick={() => void window.nix.resumeRun(current.id).then(select).catch(fail)}>Resume with checkpoint</button>}{current.status === 'review' && <button className="primary" onClick={() => void window.nix.acceptRun(current.id).catch(fail)}>Accept reviewed result</button>}<button onClick={() => void window.nix.exportLog(current.id).catch(fail)}>Export log</button></div>{artifacts.length > 0 && <div className="artifact-list"><h3>Artifacts</h3>{[...new Set(artifacts)].map(path => <button key={path} onClick={() => void window.nix.openArtifact({ runId: current.id, path }).catch(fail)}>▧ {path.split(/[\\/]/).at(-1)} · Show in folder</button>)}</div>}<div className="timeline">{events.map(event => <details key={event.id} className={`event ${event.type.includes('error') || event.type.includes('denied') ? 'event-error' : ''}`} open={event.type === 'tool.result' || event.type === 'tool.error'}><summary><span>{event.type.replaceAll('.', ' / ')}</span><time>{new Date(event.createdAt).toLocaleTimeString()}</time></summary><pre>{(() => { try { return JSON.stringify(JSON.parse(event.data), null, 2); } catch { return event.data; } })()}</pre></details>)}</div></>}</section></div>
    <div className="task-composer"><VoiceInput onText={text=>setGoal(text)}/><form onSubmit={e => { e.preventDefault(); void begin(); }}><textarea aria-label="Task goal" value={goal} maxLength={6000} onChange={e => setGoal(e.target.value)} rows={2} placeholder="Describe a file task, a script to build, or a result to verify…"/><button className="primary" disabled={!!state.active || starting || !goal.trim() || (mode !== 'mock' && !workspace)}>{starting ? 'Starting…' : 'Run task ↗'}</button></form><div className="footer-note"><span>Approval before action · Evidence before completion</span><span>12 turns / 3 failures / 10 min</span></div></div>
    {current && artifacts.some(p=>p.endsWith('.png')) && <div className="preview-controls"><label>Rendered preview <select aria-label="Rendered preview" defaultValue="" onChange={e=>{if(e.target.value)void window.nix.previewArtifact({runId:current.id,path:e.target.value}).then(setPreview).catch(fail);}}><option value="">Choose a page or slide</option>{artifacts.filter(p=>p.endsWith('.png')).map(path=><option key={path} value={path}>{path.split(/[\\/]/).at(-1)}</option>)}</select></label></div>}
    {preview && <div className="approval-backdrop"><section className="preview-dialog panel" role="dialog" aria-modal="true" aria-label="Rendered document preview"><button autoFocus onClick={()=>setPreview(null)}>Close preview</button><img src={preview} alt="Rendered document page or slide"/></section></div>}
    {approvals.length > 0 && <div className="approval-backdrop"><section className="approval-dialog panel" role="dialog" aria-modal="true" aria-labelledby="approval-title"><div className="section-label">PERMISSION GATE <span>AWAITING YOUR DECISION</span></div><h2 id="approval-title">Review proposed action</h2><h3>{approvals[0].tool}</h3><p>{approvals[0].description}</p><pre>{JSON.stringify(approvals[0].arguments, null, 2)}</pre><div className="approval-actions"><button autoFocus onClick={() => void window.nix.approve({ id: approvals[0].id, allow: false, remember: false }).catch(fail)}>Deny</button><button onClick={() => void window.nix.approve({ id: approvals[0].id, allow: true, remember: true }).catch(fail)}>Allow exact action for run</button><button className="primary" onClick={() => void window.nix.approve({ id: approvals[0].id, allow: true, remember: false }).catch(fail)}>Allow once</button></div><small>Approval is bound to this tool and these exact arguments. It expires when the run ends.</small></section></div>}
  </div>;
}
