import React,{useEffect,useRef,useState} from 'react';
export function VoiceInput({onText}:{onText:(text:string)=>void}){
  const [recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const mounted=useRef(true);
  useEffect(()=>()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());},[]);
  const toggle=async()=>{
    if(recording){recorder.current?.stop();return;}setError('');setBusy(true);
    try{const status=await window.nix.voiceStatus();if(!status.ready)throw new Error('Download local voice models in Settings first.');await window.nix.allowMicrophone();const media=await navigator.mediaDevices.getUserMedia({audio:true,video:false});if(!mounted.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const rec=new MediaRecorder(media,{mimeType:'audio/webm'});recorder.current=rec;const chunks:Blob[]=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{if(timer.current)clearTimeout(timer.current);media.getTracks().forEach(t=>t.stop());if(!mounted.current)return;setRecording(false);setBusy(true);try{const buffer=await new Blob(chunks,{type:'audio/webm'}).arrayBuffer();const text=await window.nix.transcribe(new Uint8Array(buffer));if(mounted.current)onText(text);}catch(e){if(mounted.current)setError(String(e));}finally{if(mounted.current)setBusy(false);}};rec.start();setRecording(true);timer.current=setTimeout(()=>{if(rec.state==='recording')rec.stop();},60000);}catch(e){setError(String(e));}finally{setBusy(false);}
  };
  return <span className="voice-control"><button type="button" aria-label={recording?'Stop recording':'Dictate with microphone'} disabled={busy} onClick={()=>void toggle()}>{recording?'● Stop recording':busy?'Transcribing…':'◉ Dictate'}</button>{error&&<span className="message-error" role="alert">{error}</span>}</span>;
}
export function SpeakButton({text}:{text:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const audio=useRef<HTMLAudioElement|null>(null);useEffect(()=>()=>{audio.current?.pause();},[]);return <span className="voice-control"><button type="button" disabled={busy} onClick={()=>{setError('');setBusy(true);audio.current?.pause();void window.nix.speak(text.slice(0,3000)).then(data=>{audio.current=new Audio(data);return audio.current.play();}).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}>{busy?'Preparing voice…':'▷ Read aloud'}</button><button type="button" onClick={()=>{audio.current?.pause();void window.nix.cancelVoice();}}>Stop audio</button>{error&&<span className="message-error">{error}</span>}</span>;}
